# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fiscal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fiscal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66iscal.proto\x12\x06\x66iscal\"J\n\x0bNotaRequest\x12\x12\n\nproduto_id\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\x12\x13\n\x0bvalor_total\x18\x03 \x01(\x01\"B\n\x0cNotaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x0f\n\x07nota_id\x18\x03 \x01(\t2H\n\rFiscalService\x12\x37\n\nEmitirNota\x12\x13.fiscal.NotaRequest\x1a\x14.fiscal.NotaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fiscal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTAREQUEST']._serialized_start=24
  _globals['_NOTAREQUEST']._serialized_end=98
  _globals['_NOTARESPONSE']._serialized_start=100
  _globals['_NOTARESPONSE']._serialized_end=166
  _globals['_FISCALSERVICE']._serialized_start=168
  _globals['_FISCALSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
