# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: logistica.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'logistica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flogistica.proto\x12\tlogistica\"G\n\x0c\x45nvioRequest\x12\x0f\n\x07nota_id\x18\x01 \x01(\t\x12\x12\n\nproduto_id\x18\x02 \x01(\t\x12\x12\n\nquantidade\x18\x03 \x01(\x05\"2\n\rEnvioResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2U\n\x10LogisticaService\x12\x41\n\x0c\x41gendarEnvio\x12\x17.logistica.EnvioRequest\x1a\x18.logistica.EnvioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'logistica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENVIOREQUEST']._serialized_start=30
  _globals['_ENVIOREQUEST']._serialized_end=101
  _globals['_ENVIORESPONSE']._serialized_start=103
  _globals['_ENVIORESPONSE']._serialized_end=153
  _globals['_LOGISTICASERVICE']._serialized_start=155
  _globals['_LOGISTICASERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
