# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logistica_pb2 as logistica__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in logistica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LogisticaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgendarEnvio = channel.unary_unary(
                '/logistica.LogisticaService/AgendarEnvio',
                request_serializer=logistica__pb2.EnvioRequest.SerializeToString,
                response_deserializer=logistica__pb2.EnvioResponse.FromString,
                _registered_method=True)


class LogisticaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgendarEnvio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogisticaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgendarEnvio': grpc.unary_unary_rpc_method_handler(
                    servicer.AgendarEnvio,
                    request_deserializer=logistica__pb2.EnvioRequest.FromString,
                    response_serializer=logistica__pb2.EnvioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logistica.LogisticaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logistica.LogisticaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LogisticaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgendarEnvio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logistica.LogisticaService/AgendarEnvio',
            logistica__pb2.EnvioRequest.SerializeToString,
            logistica__pb2.EnvioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
