# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pedido.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pedido.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpedido.proto\x12\x06pedido\"L\n\rPedidoRequest\x12\x12\n\nproduto_id\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\x12\x13\n\x0bvalor_total\x18\x03 \x01(\x01\"3\n\x0ePedidoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2M\n\rPedidoService\x12<\n\x0b\x43riarPedido\x12\x15.pedido.PedidoRequest\x1a\x16.pedido.PedidoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedido_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOREQUEST']._serialized_start=24
  _globals['_PEDIDOREQUEST']._serialized_end=100
  _globals['_PEDIDORESPONSE']._serialized_start=102
  _globals['_PEDIDORESPONSE']._serialized_end=153
  _globals['_PEDIDOSERVICE']._serialized_start=155
  _globals['_PEDIDOSERVICE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
